tasks:
  - name: airbyte
    init: |
      git clone https://github.com/airbytehq/airbyte.git
      cd airbyte
    command: |
      ./run-ab-platform.sh
  - name: pip
    command: |
      pip install -r requirements.txt
ports:
  - port: 8000
    