tasks:
  - name: postgres, metabase and airbyte
    init: |
      mkdir metabase-data
      mkdir pgdata
    command: |
      docker compose up -d
  - name: python
    command: |
      pyenv install 3.11.3 -f
      pyenv global 3.11.3
      python -m venv .venv
      source .venv/bin/activate
      pip install -r requirements.txt
ports:
  - name: airbyte
    port: 8000
  - name: metabase
    port: 3002
  - name: postgres
    port: 5432
    