tasks:
  - name: airbyte
    init: |
      git clone https://github.com/airbytehq/airbyte.git
      cd airbyte
      sed -i~ '/^LOCAL_ROOT=/s/=.*/="/workspace/DSSG-Data-Engineering-Workshop/airbyte_local/"/'
      sed -i~ '/^LOCAL_DOCKER_MOUNT=/s/=.*/="/workspace/DSSG-Data-Engineering-Workshop/airbyte_local/"/'
    command: |
      ./run-ab-platform.sh
  - name: pip
    command: |
      pip install -r requirements.txt
      duckdb airbyte_local/database.duckdb
ports:
  - port: 8000
    