tasks:
  - name: airbyte
    init: |
      git clone https://github.com/airbytehq/airbyte.git
      mkdir airbyte_local
      cd airbyte
      sed -i~ '/^LOCAL_ROOT=/s/=.*/="workspace/DSSG-Data-Engineering-Workshop/airbyte_local"/'
      sed -i~ '/^LOCAL_DOCKER_MOUNT=/s/=.*/="workspace/DSSG-Data-Engineering-Workshop/airbyte_local"/'
    command: |
      ./run-ab-platform.sh
  - name: python
    command: |
      pyenv global 3.11.3
      pip install -r requirements.txt
      duckdb airbyte_local/database.duckdb
ports:
  - port: 8000
    