version: "3"
services:

  postgres-db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: Pokemon
      PGDATA: /var/lib/postgresql/data
    networks:
      - airbyte_internal
      - airbyte_public
    volumes:
      # declare your mount volume /host/dir:/container/dir
      - ./pgdata:/var/lib/postgresql/data

  metabase:
    image: metabase/metabase
    restart: always
    ports:
      - 3002:3000
    networks:
      - airbyte_internal
      - airbyte_public
    volumes:
      # declare your mount volume /host/dir:/container/dir
      - ./metabase-data:/metabase-data
