site_name: DSSG Data Engineering Workshop
repo_name: Github Repo
repo_url: https://github.com/rogall-e/DSSG-Data-Engineering-Workshop
nav:
  - Home: index.md
  - Usecase: 0_getstarted/usecase.md
  - Setup:
      - Developer Setup: 0_getstarted/developer-setup.md
  - Storing Data:
      - Datastores in Organizations: 1_store/data-in-orgs.md
      - Databases: 1_store/databases.md
      - DuckDB: 1_store/duckdb.md
  - Extract and Load:
      - Material: 2_extract/material.md
  - Transform: 
      - Material: 3_transform/0_intro_transformation.md
      - From Raw to Metric: 3_transform/1_from_raw_to_metric.md
      - DBT: 3_transform/2_dbt.md
      - A DBT Workflow: 3_transform/3_a_dbt_workflow.md
  - Analyze:
      - Material: 4_analyze/dashboarding-tools.md
  - Outlook:
      - Applying your new skills: 5_outlook/applying-your-skills.md
      - Learning More: 5_outlook/learning-more.md
theme:
  language: en
  name: material
  font:
    text: Inter
    code: Roboto Mono
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      primary: deep purple
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep purple
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep purple
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  features:
    - content.code.annotate
    - content.tooltips
    - content.code.copy
    - content.tabs.link
    - navigation.indexes
    - navigation.instant.progress
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - navigation.footer
    - search.highlight
    - search.share
    - search.suggest
    - toc.fol
    - attr_list
    - md_in_htmllow
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - md_in_html
  - attr_list
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

extra_css:
  - css/termynal.css
  - css/custom.css
  - stylesheets/extra.css

extra_javascript:
  - https://unpkg.com/browse/mermaid@10.2.2/dist/mermaid.min.js
  - js/termynal.js
  - js/custom.js
